#!/bin/sh
# Applies the egress filter (root), then drops to the unprivileged user.
set -eu

RUN_AS_UID="${DEVENV_UID:-1000}"
RUN_AS_GID="${DEVENV_GID:-1000}"

if [ "$(id -u)" -eq 0 ]; then
    if [ "${DEVENV_FIREWALL:-on}" = "on" ]; then
        if ! /usr/local/bin/init-firewall.sh; then
            echo "devenv: egress filter failed to apply; refusing to start." >&2
            echo "devenv: rerun with --open to start without it." >&2
            exit 1
        fi
    else
        echo "devenv: WARNING - running without the egress filter." >&2
    fi

    # Git identity for anything that is not an agent - a plain shell, or a
    # script the user runs directly. Agents override this through the wrappers
    # in /opt/devenv/bin, which set GIT_AUTHOR_*/GIT_COMMITTER_* for their own
    # process tree. Same rule in both places: agent-<DEVENV_AGENT>, or a
    # generic sandbox identity when DEVENV_AGENT is unset.
    #
    # This lands in /etc/devenv rather than ~/.gitconfig so it does not depend
    # on who owns the home directory; GIT_CONFIG_GLOBAL points git at it.
    if [ -n "${DEVENV_AGENT:-}" ]; then
        git_identity="agent-${DEVENV_AGENT}"
    else
        git_identity="devenv"
    fi

    # core.quotePath: git escapes non-ASCII filenames as octal by default, so
    # a diff touching one becomes unreadable. The image is UTF-8; git may as
    # well print UTF-8.
    #
    # safe.directory: /app is a bind mount whose owner the container does not
    # control. Where the host uid cannot be aligned with the container user,
    # git would otherwise refuse to touch it as "dubious ownership". Only the
    # mount point itself is listed - git supports no globbing here, and the
    # blanket "*" would switch the check off altogether. A repository in a
    # subdirectory of /app on such a host needs its own entry; git prints the
    # exact command to add one.
    cat > /etc/devenv/gitconfig <<EOF
# Generated by entrypoint.sh on every container start. Edits do not survive.
[user]
	name = ${git_identity}
	email = ${git_identity}@devenv.local
[safe]
	directory = /app
[core]
	quotePath = false
EOF
    chown "${RUN_AS_UID}:${RUN_AS_GID}" /etc/devenv/gitconfig

    # Align ownership of the credential volumes with the runtime user. Docker
    # creates named volumes owned by root on first use.
    for d in /home/node/.claude /home/node/.codex /home/node/.gemini; do
        [ -d "$d" ] && chown "${RUN_AS_UID}:${RUN_AS_GID}" "$d" || true
    done

    exec setpriv \
        --reuid="${RUN_AS_UID}" \
        --regid="${RUN_AS_GID}" \
        --init-groups \
        -- "$@"
fi

exec "$@"
